apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQVI2RlBMUlUyTVpCSk9J
  VlQKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gbHozYTFFOW8vUTVadkR4bmQ1R1dK
  Z2tYSS9CZDc4V1UvRlR0dDBMZwo=   